export const CHANGE_NAME = 'CHANGE_NAME';
export const SET_NAME_DEFINED = 'SET_NAME_DEFINED';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const SET_AVATAR = 'SET_AVATAR';